version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tales
      POSTGRES_PASSWORD: 170465
      POSTGRES_DB: localhost_login_jwt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
