services:
  postgres:
    image: postgres:17
    container_name: postgres-estudo
    environment:
      POSTGRES_USER: tales
      POSTGRES_PASSWORD: 170465
      POSTGRES_DB: localhost
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
